### ISSUE TITLE
code passwword crash si y'as du texte

### ISSUE THREAD

**Issue by ilylbgg** [PolarisWolf/Password-Checker#1]
quand je mets une lettre quekquone a mon code, il va continue a chercher indéfinement 

fudrais verifier si le code contient du texte avant de commencer

**Comment by ilylbgg** [comment]
![image](https://github.com/user-attachments/assets/efe38687-2e45-4665-a0e2-bf94c021846f)

la PJ

**Comment by Awakno** [comment]
C'est corrigé
